import json
from pathlib import Path
import tempfile
import unittest

from verification_candidate import NS, export, validate

COMMIT = 'a' * 40
DATA = (f'<verification-metadata xmlns="{NS}"><configuration>'
        '<verify-metadata>true</verify-metadata><verify-signatures>false</verify-signatures>'
        '</configuration><components><component group="org.example" name="example" version="1.0">'
        '<artifact name="example-1.0.jar"><sha256 value="' + 'b' * 64 + '" origin="Generated by Gradle"/>'
        '</artifact><artifact name="example-1.0.pom"><sha256 value="' + 'c' * 64 + '"/>'
        '</artifact></component></components></verification-metadata>').encode()
ROOT = Path(__file__).resolve().parent.parent


class CandidateTest(unittest.TestCase):
    def test_exact_bytes_and_untrusted_receipt_only(self):
        with tempfile.TemporaryDirectory() as folder:
            source = Path(folder) / 'metadata.xml'
            source.write_bytes(DATA)
            out = Path(folder) / 'out'
            receipt = export(source, COMMIT, out)
            self.assertFalse(receipt['trusted'])
            self.assertEqual(receipt['artifacts'], 2)
            self.assertEqual(receipt['metadata_artifacts'], 1)
            self.assertEqual((out / 'verification-metadata.xml').read_bytes(), DATA)
            self.assertEqual(json.loads((out / 'RECEIPT.json').read_text()), receipt)
            self.assertEqual(sorted(p.name for p in out.iterdir()), ['RECEIPT.json', 'verification-metadata.xml'])
            with self.assertRaises(FileExistsError):
                export(source, COMMIT, out)

    def test_rejects_trust_bypasses_and_entity_inputs(self):
        mutations = [DATA.replace(b'>true<', b'>false<'), DATA.replace(b'>false<', b'>true<'),
                     DATA.replace(b'<components>', b'<trusted-artifacts/><components>'),
                     b'<!DOCTYPE x [<!ENTITY e "bad">]>' + DATA,
                     DATA.decode().encode('utf-16'), DATA.replace(b'example-1.0.jar', b'../private.key'),
                     DATA.replace(b'b' * 64, b'bad'), DATA.replace(b'Generated by Gradle', b'unknown origin'),
                     DATA.replace(b'example-1.0.pom', b'example-1.0.zip')]
        for data in mutations:
            with self.subTest(data=data[:50]), self.assertRaises((ValueError, UnicodeError)):
                validate(data, COMMIT)
        with self.assertRaises(ValueError):
            validate(DATA, 'short')

    def test_rejects_input_symlink_without_export(self):
        with tempfile.TemporaryDirectory() as folder:
            source = Path(folder) / 'metadata.xml'
            source.write_bytes(DATA)
            link = Path(folder) / 'link'
            link.symlink_to(source)
            out = Path(folder) / 'out'
            with self.assertRaises(ValueError):
                export(link, COMMIT, out)
            self.assertFalse(out.exists())

    def test_manual_only_unsigned_public_allowlist(self):
        workflow = (ROOT / '.github/workflows/dependency-audit.yml').read_text()
        self.assertIn('type: boolean\n        required: false\n        default: false', workflow)
        condition = "if: github.event_name == 'workflow_dispatch' && inputs.verification_candidate == true"
        self.assertEqual(workflow.count(condition), 2)
        self.assertIn('test ! -e gradle/verification-metadata.xml', workflow)
        self.assertIn('--no-build-cache --rerun-tasks', workflow)
        self.assertIn('--write-verification-metadata sha256', workflow)
        self.assertNotIn(' --dry-run', next(line for line in workflow.splitlines() if '--write-verification-metadata sha256' in line))
        self.assertNotIn('${{ secrets.', workflow)
        self.assertNotIn('contents: write', workflow)
        self.assertNotIn('id-token: write', workflow)
        candidate = workflow.split('name: Upload untrusted public verification candidate for review', 1)[1]
        self.assertIn('/verification-metadata.xml', candidate)
        self.assertIn('/RECEIPT.json', candidate)
        self.assertNotIn('*', candidate)
        self.assertNotIn('continue-on-error:', workflow)
        self.assertFalse((ROOT / 'gradle/verification-metadata.xml').exists())


if __name__ == '__main__':
    unittest.main()
