"""Validate/export an UNTRUSTED public Gradle checksum candidate; never a trust approval."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import stat
import xml.etree.ElementTree as ET

NS = 'https://schema.gradle.org/dependency-verification'
XSI = 'http://www.w3.org/2001/XMLSchema-instance'
MAX_BYTES = 16 * 1024 * 1024
TASKS = [':app:compileDebugKotlin', ':app:compileReleaseKotlin', ':app:testDebugUnitTest',
         ':app:testReleaseUnitTest', ':app:lintDebug', ':app:lintRelease',
         ':baselineprofile:compileBenchmarkKotlin']


def validate(data, commit):
    if not re.fullmatch(r'[0-9a-f]{40}', commit):
        raise ValueError('Expected full commit SHA')
    if not data or len(data) > MAX_BYTES:
        raise ValueError('Candidate size outside bound')
    # Reject declarations before XML parsing, including UTF-16/32 obfuscation.
    text = data.decode('utf-8')
    if '<!DOCTYPE' in text.upper() or '<!ENTITY' in text.upper() or '\x00' in text:
        raise ValueError('DTD/entity/binary input forbidden')
    root = ET.fromstring(text)
    if root.tag != f'{{{NS}}}verification-metadata':
        raise ValueError('Expected Gradle verification root')
    if set(root.attrib) - {f'{{{XSI}}}schemaLocation'}:
        raise ValueError('Unexpected root attributes')
    schema = root.get(f'{{{XSI}}}schemaLocation', '')
    if schema and schema != NS + ' ' + NS + '/dependency-verification-1.3.xsd':
        raise ValueError('Unexpected schema location')
    if [e.tag for e in root] != [f'{{{NS}}}configuration', f'{{{NS}}}components']:
        raise ValueError('Expected only configuration and components')
    config, components = root
    if config.attrib or components.attrib:
        raise ValueError('Unexpected section attributes')
    if [(e.tag, (e.text or '').strip()) for e in config] != [
        (f'{{{NS}}}verify-metadata', 'true'), (f'{{{NS}}}verify-signatures', 'false')]:
        raise ValueError('Metadata checks required; checksum-only generation expected')
    if any(e.attrib or len(e) for e in config):
        raise ValueError('Unexpected configuration content')
    for node in root.iter():
        if node.tag not in (f'{{{NS}}}verify-metadata', f'{{{NS}}}verify-signatures') and (node.text or '').strip():
            raise ValueError('Unexpected XML text')
        if (node.tail or '').strip():
            raise ValueError('Unexpected XML tail')
    artifacts = checksums = metadata = 0
    names = set()
    for component in components:
        if component.tag != f'{{{NS}}}component' or set(component.attrib) != {'group', 'name', 'version'}:
            raise ValueError('Invalid component')
        identity = tuple(component.get(k) for k in ('group', 'name', 'version'))
        if identity in names or any(not v or len(v) > 512 or not all(32 <= ord(c) <= 126 for c in v) for v in identity):
            raise ValueError('Invalid/duplicate public coordinate')
        names.add(identity)
        files = set()
        for artifact in component:
            name = artifact.get('name', '')
            if (artifact.tag != f'{{{NS}}}artifact' or set(artifact.attrib) != {'name'} or
                    not re.fullmatch(r'[A-Za-z0-9_.+\-]+', name) or '..' in name or name in files):
                raise ValueError('Invalid/duplicate artifact basename')
            files.add(name)
            artifacts += 1
            metadata += name.endswith(('.pom', '.module', '.ivy'))
            if not len(artifact):
                raise ValueError('Missing checksum')
            for checksum in artifact:
                if (checksum.tag != f'{{{NS}}}sha256' or set(checksum.attrib) - {'value', 'origin'} or
                        not re.fullmatch(r'[0-9a-f]{64}', checksum.get('value', '')) or
                        checksum.get('origin') not in (None, 'Generated by Gradle')):
                    raise ValueError('Invalid generated checksum')
                checksums += 1
                for alternative in checksum:
                    if (alternative.tag != f'{{{NS}}}also-trust' or set(alternative.attrib) != {'value'} or
                            len(alternative) or not re.fullmatch(r'[0-9a-f]{64}', alternative.get('value', ''))):
                        raise ValueError('Invalid alternative checksum')
                    checksums += 1
        if not files:
            raise ValueError('Empty component')
    if not names or not artifacts or not metadata:
        raise ValueError('Candidate must contain artifacts and metadata')
    return {'schema': 1, 'commit': commit, 'bytes': len(data),
            'sha256': hashlib.sha256(data).hexdigest(), 'components': len(names),
            'artifacts': artifacts, 'checksum_values': checksums, 'metadata_artifacts': metadata,
            'tasks': TASKS, 'trusted': False,
            'scope': 'Observed unsigned build-task checksums, NOT independent publisher authentication. '
                     'Candidate only; no verification policy enabled. Does not cover diagnostic helper, '
                     'APK signing/assembly, every detached resolution, SDK/JDK executables or generated caches.'}


def export(source, commit, destination):
    source = Path(source)
    info = source.lstat()
    if not stat.S_ISREG(info.st_mode) or info.st_size > MAX_BYTES:
        raise ValueError('Expected bounded regular metadata file, not symlink')
    with source.open('rb') as stream:
        data = stream.read(MAX_BYTES + 1)
    receipt = validate(data, commit)
    # Emit the validated public tree only: comments/PIs from input are never uploaded.
    ET.register_namespace('', NS)
    ET.register_namespace('xsi', XSI)
    public = ET.tostring(ET.fromstring(data), encoding='utf-8', xml_declaration=True)
    receipt['source_sha256'] = receipt['sha256']
    receipt['source_bytes'] = receipt['bytes']
    receipt['sha256'] = hashlib.sha256(public).hexdigest()
    receipt['bytes'] = len(public)
    destination = Path(destination)
    if destination.is_symlink():
        raise ValueError('Output directory must not be a symlink')
    destination.mkdir(parents=True, exist_ok=True)
    # Fixed files only, exclusive creation: no recursive upload or secret/cache glob.
    with (destination / 'verification-metadata.xml').open('xb') as stream:
        stream.write(public)
    with (destination / 'RECEIPT.json').open('x') as stream:
        json.dump(receipt, stream, sort_keys=True, indent=2)
        stream.write('\n')
    return receipt


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source')
    parser.add_argument('--commit', required=True)
    parser.add_argument('--out', required=True)
    args = parser.parse_args()
    try:
        receipt = export(args.source, args.commit, args.out)
        print(json.dumps(receipt, sort_keys=True))
    except (OSError, ValueError, ET.ParseError, UnicodeError) as error:
        parser.exit(1, f'Candidate validation failed: {error}\n')


if __name__ == '__main__':
    main()
